package com.dmvmotor.api.practice.controller;

import com.dmvmotor.api.common.ApiResponse;
import com.dmvmotor.api.common.CurrentUser;
import com.dmvmotor.api.content.domain.Choice;
import com.dmvmotor.api.content.domain.QuestionDetail;
import com.dmvmotor.api.practice.application.PracticeService;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/practice/sessions")
public class PracticeSessionController {

    private final PracticeService practiceService;

    public PracticeSessionController(PracticeService practiceService) {
        this.practiceService = practiceService;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public ApiResponse<?> startSession(@CurrentUser Long userId,
                                        @Valid @RequestBody StartRequest req) {
        var result = practiceService.startSession(userId, req.entryType(),
                req.language() != null ? req.language() : "en");
        return ApiResponse.ok(Map.of(
                "sessionId",    String.valueOf(result.sessionId()),
                "entryType",    result.entryType(),
                "status",       result.status(),
                "language",     result.language(),
                "nextQuestion", toQuestionDto(result.nextQuestion())
        ));
    }

    @GetMapping("/{id}/next-question")
    public ApiResponse<?> nextQuestion(@PathVariable Long id) {
        QuestionDetail q = practiceService.getNextQuestion(id);
        int answered = practiceService.getSessionStatus(id).answeredCount();
        return ApiResponse.ok(Map.of(
                "questionId", String.valueOf(q.questionId()),
                "variantId",  String.valueOf(q.variantId()),
                "stem",       q.stem(),
                "choices",    q.choices(),
                "progress",   Map.of("answeredCount", answered)
        ));
    }

    @GetMapping("/{id}")
    public ApiResponse<?> getSession(@PathVariable Long id) {
        var status = practiceService.getSessionStatus(id);
        return ApiResponse.ok(Map.of(
                "sessionId",    String.valueOf(status.sessionId()),
                "status",       status.status(),
                "answeredCount", status.answeredCount(),
                "totalCount",   status.totalCount()
        ));
    }

    @PostMapping("/{id}/answers")
    public ApiResponse<?> submitAnswer(@PathVariable Long id,
                                        @Valid @RequestBody AnswerRequest req) {
        var result = practiceService.submitAnswer(id,
                Long.parseLong(req.questionId()),
                Long.parseLong(req.variantId()),
                req.selectedChoiceKey());
        return ApiResponse.ok(Map.of(
                "questionId",       String.valueOf(result.questionId()),
                "isCorrect",        result.isCorrect(),
                "correctChoiceKey", result.correctChoiceKey(),
                "explanation",      result.explanation() != null ? result.explanation() : "",
                "progress",         Map.of("answeredCount", result.answeredCount())
        ));
    }

    @PostMapping("/{id}/complete")
    public ApiResponse<?> completeSession(@PathVariable Long id) {
        var result = practiceService.completeSession(id);
        return ApiResponse.ok(Map.of(
                "sessionId", String.valueOf(result.sessionId()),
                "status",    result.status()
        ));
    }

    // ---------------------------------------------------------------
    // DTOs
    // ---------------------------------------------------------------

    record StartRequest(
            @NotBlank(message = "must not be blank") String entry_type,
            String language
    ) {
        String entryType() { return entry_type; }
        // language() auto-generated by record; null-safe handled in controller
    }

    record AnswerRequest(
            @NotBlank String question_id,
            @NotBlank String variant_id,
            @NotBlank String selected_choice_key
    ) {
        String questionId()      { return question_id; }
        String variantId()       { return variant_id; }
        String selectedChoiceKey() { return selected_choice_key; }
    }

    private Map<String, Object> toQuestionDto(QuestionDetail q) {
        return Map.of(
                "questionId", String.valueOf(q.questionId()),
                "variantId",  String.valueOf(q.variantId()),
                "stem",       q.stem(),
                "choices",    q.choices()
        );
    }
}
