package com.dmvmotor.api.mistakereview.review.controller;

import com.dmvmotor.api.common.ApiResponse;
import com.dmvmotor.api.common.BusinessException;
import com.dmvmotor.api.common.CurrentUser;
import com.dmvmotor.api.common.Ids;
import com.dmvmotor.api.content.domain.QuestionDetail;
import com.dmvmotor.api.mistakereview.review.application.ReviewService;
import com.dmvmotor.api.mistakereview.review.application.ReviewService.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/v1/review")
public class ReviewController {

    private final ReviewService reviewService;

    public ReviewController(ReviewService reviewService) {
        this.reviewService = reviewService;
    }

    @GetMapping("/pack")
    public ApiResponse<?> getReviewPack(@CurrentUser Long userId) {
        requireAuth(userId);
        ReviewPackResult pack = reviewService.getOrCreatePack(userId);
        return ApiResponse.ok(Map.of(
                "review_pack_id",          String.valueOf(pack.packId()),
                "status",                  pack.status(),
                "target_question_count",   pack.targetQuestionCount(),
                "completed_question_count", pack.completedQuestionCount(),
                "tasks",                   pack.tasks().stream().map(this::toTaskDto).toList()
        ));
    }

    @GetMapping("/tasks/{id}/questions")
    public ApiResponse<?> getTaskQuestions(
            @CurrentUser Long userId,
            @PathVariable Long id,
            @RequestParam(defaultValue = "en") String language
    ) {
        requireAuth(userId);
        TaskQuestionsResult result = reviewService.getTaskQuestions(id, userId, language);
        return ApiResponse.ok(Map.of(
                "review_task_id", String.valueOf(result.taskId()),
                "task_type",      result.taskType(),
                "topic_id",       String.valueOf(result.topicId()),
                "questions",      result.questions().stream().map(this::toQuestionDto).toList()
        ));
    }

    @PostMapping("/tasks/{id}/answers")
    public ApiResponse<?> submitAnswer(
            @CurrentUser Long userId,
            @PathVariable Long id,
            @Valid @RequestBody AnswerRequest req
    ) {
        requireAuth(userId);
        ReviewAnswerResult result = reviewService.submitAnswer(
                id, userId,
                Ids.parse(req.questionId(), "question_id"),
                Ids.parse(req.variantId(), "variant_id"),
                req.selectedChoiceKey(),
                req.language()); // null if caller omits the field; service falls back to user preference
        return ApiResponse.ok(Map.of(
                "question_id",        String.valueOf(result.questionId()),
                "is_correct",         result.isCorrect(),
                "correct_choice_key", result.correctChoiceKey(),
                "explanation",        result.explanation() != null ? result.explanation() : "",
                "task_progress",      Map.of(
                        "answered_count", result.answeredCount(),
                        "target_count",  result.targetCount()
                )
        ));
    }

    @PostMapping("/tasks/{id}/complete")
    public ApiResponse<?> completeTask(
            @CurrentUser Long userId,
            @PathVariable Long id
    ) {
        requireAuth(userId);
        CompleteTaskResult result = reviewService.completeTask(id, userId);
        return ApiResponse.ok(Map.of(
                "review_task_id", String.valueOf(result.taskId()),
                "completed",      result.completed(),
                "next_action",    Map.of("type", "continue_review", "label", "Continue review")
        ));
    }

    // ---------------------------------------------------------------
    // DTOs
    // ---------------------------------------------------------------

    record AnswerRequest(
            @NotBlank String question_id,
            @NotBlank String variant_id,
            @NotBlank String selected_choice_key,
            String language
    ) {
        String questionId()       { return question_id; }
        String variantId()        { return variant_id; }
        String selectedChoiceKey(){ return selected_choice_key; }
        // language() accessor is auto-generated by the record (returns the language component).
    }

    private Map<String, Object> toTaskDto(TaskSummary t) {
        return Map.of(
                "review_task_id",           String.valueOf(t.taskId()),
                "topic_id",                 String.valueOf(t.topicId()),
                "type",                     t.type(),
                "status",                   t.status(),
                "priority",                 t.priority(),
                "target_question_count",    t.targetQuestionCount(),
                "completed_question_count", t.completedQuestionCount()
        );
    }

    private Map<String, Object> toQuestionDto(QuestionDetail q) {
        return Map.of(
                "question_id", String.valueOf(q.questionId()),
                "variant_id",  String.valueOf(q.variantId()),
                "stem",        q.stem(),
                "choices",     q.choices()
        );
    }

    private void requireAuth(Long userId) {
        if (userId == null) {
            throw new BusinessException("UNAUTHORIZED", "Authentication required",
                    HttpStatus.UNAUTHORIZED);
        }
    }
}
